/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('characteristic').insert([
    {
      id: 1,
      group: 'Cultural workplace characteristics',
      type: 'Workplace Experience',
      name: 'Work-life balance',
      full_description: '',
      short_description: 'I am able to balance work demands and my personal life',
    },
    {
      id: 2,
      group: 'Cultural workplace characteristics',
      type: 'Workplace Experience',
      name: 'Diversity',
      full_description: '',
      short_description: 'My colleagues are of different backgrounds, religion, sexual orientation, etc.',
    },
    {
      id: 3,
      group: 'Cultural workplace characteristics',
      type: 'Workplace Experience',
      name: 'Trust',
      full_description: '',
      short_description: 'I feel there is a culture of honesty, respect, and psychological safety at work',
    },
    {
      id: 4,
      group: 'Cultural workplace characteristics',
      type: 'Workplace Experience',
      name: 'Remote flexibility',
      full_description: '',
      short_description: 'I am able to decide when I work remotely and when I work at the office (this can include fully remote options)',
    },
    {
      id: 5,
      group: 'Cultural workplace characteristics',
      type: 'Workplace Experience',
      name: 'Inclusive environment',
      full_description: '',
      short_description: 'My workplace treats everyone with dignity and fairness, is free of harassment and discrimination, and believes diversity brings our organization a wealth of experience that builds a better team.',
    },
    {
      id: 6,
      group: 'Cultural workplace characteristics',
      type: 'Workplace Experience',
      name: 'Young & fun environment',
      full_description: '',
      short_description: '',
    },
    {
      id: 7,
      group: 'Cultural workplace characteristics',
      type: 'Personal Growth',
      name: 'Growth opportunies',
      full_description: '',
      short_description: '',
    },
    {
      id: 8,
      group: 'Cultural workplace characteristics',
      type: 'Personal Growth',
      name: 'Work Satisfaction',
      full_description: '',
      short_description: '',
    },
    {
      id: 9,
      group: 'Cultural workplace characteristics',
      type: 'Personal Growth',
      name: 'Managerial Support',
      full_description: '',
      short_description: '',
    },
    {
      id: 10,
      group: 'Cultural workplace characteristics',
      type: 'Personal Growth',
      name: 'Diverse leadership',
      full_description: '',
      short_description: '',
    },
    {
      id: 11,
      group: 'Cultural workplace characteristics',
      type: 'Personal Growth',
      name: 'Mentorship',
      full_description: '',
      short_description: '',
    },
    {
      id: 12,
      group: 'Cultural workplace characteristics',
      type: 'Personal Growth',
      name: 'Team support',
      full_description: '',
      short_description: '',
    },
    {
      id: 13,
      group: 'Cultural workplace characteristics',
      type: 'Personal Growth',
      name: 'Collaborative environment',
      full_description: '',
      short_description: '',
    },
    {
      id: 14,
      group: 'Traditional workplace characteristics',
      type: 'Traditional',
      name: 'Compensation',
      full_description: '',
      short_description: '',
    },
    {
      id: 15,
      group: 'Traditional workplace characteristics',
      type: 'Traditional',
      name: 'Personal/ vacation time',
      full_description: '',
      short_description: '',
    },
    {
      id: 16,
      group: 'Traditional workplace characteristics',
      type: 'Traditional',
      name: 'Executive team',
      full_description: '',
      short_description: '',
    },
    {
      id: 17,
      group: 'Traditional workplace characteristics',
      type: 'Traditional',
      name: 'Benefits & perks',
      full_description: '',
      short_description: '',
    },
    {
      id: 18,
      group: 'Traditional workplace characteristics',
      type: 'Traditional',
      name: 'Job security',
      full_description: '',
      short_description: '',
    },
    {
      id: 19,
      group: 'Traditional workplace characteristics',
      type: 'Traditional',
      name: 'Interview process',
      full_description: '',
      short_description: '',
    },
  ]);
};
