/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('characteristic').insert([
    {
      id: 1,
      group: 'Cultural workplace characteristics',
      type: 'Workplace Experience',
      name: 'Work-life balance',
      full_description: '',
      short_description: 'I am able to balance work demands and my personal life',
    },
    {
      id: 2,
      group: 'Cultural workplace characteristics',
      type: 'Workplace Experience',
      name: 'Diversity',
      full_description: '',
      short_description: 'My colleagues are of different backgrounds, religion, sexual orientation, etc.',
    },
    {
      id: 3,
      group: 'Cultural workplace characteristics',
      type: 'Workplace Experience',
      name: 'Trust',
      full_description: '',
      short_description: 'I feel there is a culture of honesty, respect, and psychological safety at work',
    },
    {
      id: 4,
      group: 'Cultural workplace characteristics',
      type: 'Workplace Experience',
      name: 'Remote flexibility',
      full_description: '',
      short_description: 'I am able to decide when I work remotely and when I work at the office (this can include fully remote options).',
    },
    {
      id: 5,
      group: 'Cultural workplace characteristics',
      type: 'Workplace Experience',
      name: 'Inclusive environment',
      full_description: '',
      short_description: 'My workplace treats everyone with dignity and fairness, is free of harassment and discrimination, and believes diversity brings our organization a wealth of experience that builds a better team.',
    },
    {
      id: 6,
      group: 'Cultural workplace characteristics',
      type: 'Workplace Experience',
      name: 'Young & fun environment',
      full_description: '',
      short_description: 'I am friendly with my co-workers and enjoy collaborating on projects.  We all address each other by our first names.',
    },
    {
      id: 7,
      group: 'Cultural workplace characteristics',
      type: 'Personal Growth',
      name: 'Growth opportunies',
      full_description: '',
      short_description: 'My company encourages employees to learn and grow, and has career paths available to me.',
    },
    {
      id: 8,
      group: 'Cultural workplace characteristics',
      type: 'Personal Growth',
      name: 'Work Satisfaction',
      full_description: '',
      short_description: 'I feel good about the work I do, it is valued, meaningful and has purpose.',
    },
    {
      id: 9,
      group: 'Cultural workplace characteristics',
      type: 'Personal Growth',
      name: 'Managerial Support',
      full_description: '',
      short_description: 'My managers have my back when I come to them with issues, and they take my opinion into account.',
    },
    {
      id: 10,
      group: 'Cultural workplace characteristics',
      type: 'Personal Growth',
      name: 'Diverse leadership',
      full_description: '',
      short_description: 'I see people of various backgrounds in positions of leadership.',
    },
    {
      id: 11,
      group: 'Cultural workplace characteristics',
      type: 'Personal Growth',
      name: 'Mentorship',
      full_description: '',
      short_description: 'I can easily find someone to coach me and help me learn and grow.',
    },
    {
      id: 12,
      group: 'Cultural workplace characteristics',
      type: 'Personal Growth',
      name: 'Team support',
      full_description: '',
      short_description: 'My team supports each other as we collaborate, and communicate freely together.',
    },
    {
      id: 13,
      group: 'Cultural workplace characteristics',
      type: 'Personal Growth',
      name: 'Collaborative environment',
      full_description: '',
      short_description: 'We are encouraged to work together in a cross-functional manner and utilize our different skill sets to achieve goals and solve problems.  ',
    },
    {
      id: 14,
      group: 'Traditional workplace characteristics',
      type: 'Traditional',
      name: 'Compensation',
      full_description: '',
      short_description: 'I work with people who look like me and also people who don’t look like me.',
    },
    {
      id: 15,
      group: 'Traditional workplace characteristics',
      type: 'Traditional',
      name: 'Personal/ vacation time',
      full_description: '',
      short_description: 'Vacation and/or Personal time is available and time off is encouraged.',
    },
    {
      id: 16,
      group: 'Traditional workplace characteristics',
      type: 'Traditional',
      name: 'Executive team',
      full_description: '',
      short_description: 'In general, I agree with the decisions and vision for the company made by the executive team.  They are supportive in guiding the organization to reach those goals.',
    },
    {
      id: 17,
      group: 'Traditional workplace characteristics',
      type: 'Traditional',
      name: 'Benefits & perks',
      full_description: '',
      short_description: 'I am happy with the benefits and perks I get from my company.',
    },
    {
      id: 18,
      group: 'Traditional workplace characteristics',
      type: 'Traditional',
      name: 'Job security',
      full_description: '',
      short_description: 'I am confident I will have this job for the foreseeable future.',
    },
    {
      id: 19,
      group: 'Traditional workplace characteristics',
      type: 'Traditional',
      name: 'Interview process',
      full_description: '',
      short_description: 'I was told what the interview process was, and I was updated on the status of my application in a timely manner.',
    },
  ]);
};
